all: part1 part2 part3

part1: customshell_part1.c
	gcc -o part1 customshell_part1.c -g

part2: customshell_part2.c
	gcc -o part2 customshell_part2.c -g

part3: customshell_part3.c
	gcc -o part3 customshell_part3.c -g

clean:
	rm part*
